on:
  workflow_dispatch:
    inputs:
      test_suit:
        description: Test suit
        type: choice
        options:
          - functional
          - regression

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run selected test suite
        run: echo "Running ${{ github.event.inputs.test_suite }} tests"
