name: test flow
on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: "manual trigger"
        required: true
        type: choice
        default: functional
        options:
          - functional
          - regression
